### ISSUE TITLE
 jot: command not found

### ISSUE THREAD

**Issue by andyyuan78** [npow/MemN2N#2]
envy@ub1404envy:/media/envy/data1t/github/MemN2N$ rmdir result
envy@ub1404envy:/media/envy/data1t/github/MemN2N$ bash run.sh 
running task: 1
run.sh: line 6: jot: command not found
running task: 2
run.sh: line 6: jot: command not found
running task: 3
run.sh: line 6: jot: command not found
running task: 4
run.sh: line 6: jot: command not found
running task: 5
run.sh: line 6: jot: command not found
running task: 6
run.sh: line 6: jot: command not found
running task: 9
run.sh: line 6: jot: command not found
running task: 10
run.sh: line 6: jot: command not found
running task: 11
run.sh: line 6: jot: command not found
running task: 12
run.sh: line 6: jot: command not found
running task: 13
run.sh: line 6: jot: command not found
running task: 14
run.sh: line 6: jot: command not found
running task: 15
run.sh: line 6: jot: command not found
running task: 16
run.sh: line 6: jot: command not found
running task: 17
run.sh: line 6: jot: command not found
running task: 18
run.sh: line 6: jot: command not found
running task: 20
run.sh: line 6: jot: command not found

real    0m0.007s
user    0m0.000s
sys 0m0.000s
grep: results/1_*.txt: No such file or directory

^C
envy@ub1404envy:/media/envy/data1t/github/MemN2N$

**Comment by npow** [comment]
Got rid of `jot`.
